#------------------------------------------------------------------------------
#--  This file is a part of the LPP VHDL IP LIBRARY
#--  Copyright (C) 2010, Laboratory of Plasmas Physic - CNRS
#--
#--  This program is free software; you can redistribute it and/or modify
#--  it under the terms of the GNU General Public License as published by
#--  the Free Software Foundation; either version 3 of the License, or
#--  (at your option) any later version.
#--
#--  This program is distributed in the hope that it will be useful,
#--  but WITHOUT ANY WARRANTY; without even the implied warranty of
#--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#--  GNU General Public License for more details.
#--
#--  You should have received a copy of the GNU General Public License
#--  along with this program; if not, write to the Free Software
#--  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
#------------------------------------------------------------------------------

include ../rules.mk



all:
	make all -C AMBA
	make all -C LCD
	make all -C DAC
	make all -C FIFO
	make all -C UART
	make all -C FFT
	make all -C DELAY
	make all -C GPIO
	make all -C ADC
	make all -C MATRIX


cleanall:
	make clean -C AMBA
	make clean -C LCD
	make clean -C DAC
	make clean -C FIFO
	make clean -C UART
	make clean -C FFT
	make clean -C DELAY
	make clean -C GPIO
	make clean -C ADC
	make clean -C MATRIX

