new_project -name top -folder . -createimpl_name precision
setup_design -manufacturer Actel -family PROASIC3 -part PROASIC3 -package {484 FBGA} -speed Std
set_input_dir .
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/stdlib/version.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/stdlib/config.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/stdlib/stdlib.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/sparc/sparc.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/modgen/multlib.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/modgen/leaves.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/amba/amba.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/amba/devices.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/amba/defmst.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/amba/apbctrl.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/amba/ahbctrl.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/amba/dma2ahb_pkg.vhd
add_input_file -format VHDL -work grlib ../../../grlib-gpl-1.1.0-b4108/lib/grlib/amba/dma2ahb.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/gencomp/gencomp.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/gencomp/netcomp.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/inferred/memory_inferred.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/inferred/ddr_inferred.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/inferred/mul_inferred.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/inferred/ddr_phy_inferred.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/dware/mul_dware.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/proasic3/memory_apa3.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/proasic3/buffer_apa3.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/proasic3/clkgen_proasic3.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/proasic3/tap_proasic3.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/allclkgen.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/allddr.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/allmem.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/allmul.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/allpads.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/alltap.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/clkgen.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/clkmux.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/clkand.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/ddr_ireg.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/ddr_oreg.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/ddrphy.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/syncram.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/syncram64.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/syncram_2p.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/syncram_dp.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/syncfifo.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/regfile_3p.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/tap.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/techbuf.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/nandtree.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/clkpad.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/clkpad_ds.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/inpad.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/inpad_ds.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/iodpad.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/iopad.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/iopad_ds.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/lvds_combo.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/odpad.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/outpad.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/outpad_ds.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/toutpad.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/skew_outpad.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/grspwc_net.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/grspwc2_net.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/grlfpw_net.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/grfpw_net.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/leon4_net.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/mul_61x61.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/cpu_disas_net.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/grusbhc_net.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/ringosc.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/ssrctrl_net.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/system_monitor.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/grgates.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/inpad_ddr.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/outpad_ddr.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/iopad_ddr.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/syncram128bw.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/syncram128.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/syncram156bw.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/techmult.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/spictrl_net.vhd
add_input_file -format VHDL -work techmap ../../../grlib-gpl-1.1.0-b4108/lib/techmap/maps/scanreg.vhd
add_input_file -format VHDL -work spw ../../../grlib-gpl-1.1.0-b4108/lib/spw/comp/spwcomp.vhd
add_input_file -format VHDL -work spw ../../../grlib-gpl-1.1.0-b4108/lib/spw/wrapper/grspw_gen.vhd
add_input_file -format VHDL -work spw ../../../grlib-gpl-1.1.0-b4108/lib/spw/wrapper/grspw2_gen.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/comp/ethcomp.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/core/greth_pkg.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/core/eth_rstgen.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/core/eth_edcl_ahb_mst.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/core/eth_ahb_mst.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/core/greth_tx.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/core/greth_rx.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/core/grethc.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/wrapper/greth_gen.vhd
add_input_file -format VHDL -work eth ../../../grlib-gpl-1.1.0-b4108/lib/eth/wrapper/greth_gbit_gen.vhd
add_input_file -format VHDL -work opencores ../../../grlib-gpl-1.1.0-b4108/lib/opencores/occomp/occomp.vhd
add_input_file -format VHDL -work opencores ../../../grlib-gpl-1.1.0-b4108/lib/opencores/can/cancomp.vhd
add_input_file -format VHDL -work opencores ../../../grlib-gpl-1.1.0-b4108/lib/opencores/can/can_top.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/arith/arith.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/arith/mul32.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/arith/div32.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/memctrl/memctrl.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/memctrl/sdctrl.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/memctrl/sdctrl64.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/memctrl/sdmctrl.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/memctrl/srctrl.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/memctrl/spimctrl.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/leon3.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmuconfig.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmuiface.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/libmmu.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/libiu.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/libcache.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/libproc3.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/cachemem.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmu_icache.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmu_dcache.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmu_acache.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmutlbcam.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmulrue.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmulru.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmutlb.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmutw.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmu.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mmu_cache.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/cpu_disasx.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/iu3.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/grfpwx.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/mfpwx.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/grlfpwx.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/tbufmem.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/dsu3x.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/dsu3.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/proc3.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/leon3s.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/leon3cg.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/irqmp.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/grfpwxsh.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/grfpushwx.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3/leon3sh.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/leon3ft/leon3ft.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/can/can.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/can/can_mod.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/can/can_oc.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/can/can_mc.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/can/canmux.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/can/can_rd.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/misc.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/rstgen.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/gptimer.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/ahbram.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/ahbdpram.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/ahbtrace.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/ahbtrace_mb.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/ahbtrace_mmb.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/ahbmst.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/grgpio.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/ahbstat.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/logan.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/apbps2.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/charrom_package.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/charrom.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/apbvga.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/svgactrl.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/i2cmst_gen.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/spictrlx.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/spictrl.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/i2cslv.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/wild.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/wild2ahb.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/grsysmon.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/gracectrl.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/grgpreg.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/ahbmst2.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/misc/ahb_mst_iface.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/net/net.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/uart/uart.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/uart/libdcom.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/uart/apbuart.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/uart/dcom.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/uart/dcom_uart.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/uart/ahbuart.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/jtag/jtag.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/jtag/libjtagcom.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/jtag/jtagcom.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/jtag/ahbjtag.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/jtag/ahbjtag_bsd.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/jtag/bscanregs.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/jtag/bscanregsbd.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/greth/ethernet_mac.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/greth/greth.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/greth/greth_mb.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/greth/greth_gbit.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/greth/greth_gbit_mb.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/greth/grethm.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/spacewire/spacewire.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/spacewire/grspw.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/spacewire/grspw2.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/spacewire/grspwm.vhd
add_input_file -format VHDL -work gaisler ../../../grlib-gpl-1.1.0-b4108/lib/gaisler/gr1553b/gr1553b_pkg.vhd
add_input_file -format VHDL -work esa ../../../grlib-gpl-1.1.0-b4108/lib/esa/memoryctrl/memoryctrl.vhd
add_input_file -format VHDL -work esa ../../../grlib-gpl-1.1.0-b4108/lib/esa/memoryctrl/mctrl.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./amba_lcd_16x2_ctrlr/FRAME_CLK.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./amba_lcd_16x2_ctrlr/LCD_16x2_CFG.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./amba_lcd_16x2_ctrlr/LCD_16x2_DRVR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./amba_lcd_16x2_ctrlr/LCD_16x2_ENGINE.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./amba_lcd_16x2_ctrlr/LCD_2x16_DRIVER.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./amba_lcd_16x2_ctrlr/LCD_CLK_GENERATOR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./amba_lcd_16x2_ctrlr/Top_LCD.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./amba_lcd_16x2_ctrlr/amba_lcd_16x2_ctrlr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./amba_lcd_16x2_ctrlr/apb_lcd_ctrlr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/APB_IIR_CEL.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/APB_IIR_Filter.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/FILTER.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/FILTER_RAM_CTRLR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/FILTERcfg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/FilterCTRLR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/IIR_CEL_CTRLR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/IIR_CEL_CTRLR_v2.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/IIR_CEL_CTRLR_v2_CONTROL.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/IIR_CEL_CTRLR_v2_DATAFLOW.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/IIR_CEL_FILTER.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/RAM.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/RAM_CEL.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/RAM_CEL_N.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/RAM_CTRLR2.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/RAM_CTRLR_v2.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/Top_Filtre_IIR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/Top_IIR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/iir_filter/iir_filter.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_downsampling/Downsampling.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/APB_FFT.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/APB_FFT_half.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/Driver_FFT.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/FFT.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/FFT.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/FFTamont.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/FFTaval.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/Flag_Extremum.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/Flag_Extremum.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/Linker_FFT.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./dsp/lpp_fft/lpp_fft.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/ADDRcntr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/ALU.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/Adder.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/Clk_Divider2.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/Clk_divider.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/MAC.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/MAC_CONTROLER.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/MAC_MUX.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/MAC_MUX2.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/MAC_REG.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/MUX2.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/MUXN.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/Multiplier.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/REG.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/SYNC_FF.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/Shifter.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/TwoComplementer.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/general_purpose.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_AMR/APB_AMR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_AMR/Clock_multi.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_AMR/Dephaseur.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_AMR/Gene_Rz.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_AMR/bclk_reg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_AMR/lpp_AMR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_balise/APB_Balise.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_balise/lpp_balise.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_delay/APB_Delay.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_delay/TimerDelay.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./general_purpose/lpp_delay/lpp_delay.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lfr_time_management/apb_lfr_time_management.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lfr_time_management/lfr_time_management.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lfr_time_management/lpp_lfr_time_management.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/AD7688_drvr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/AD7688_drvr_sync.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/AD7688_spi_if.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/ADS1274_drvr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/ADS1278_drvr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/ADS7886_drvr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/RHF1401.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/WriteGen_ADC.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/dual_ADS1278_drvr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/lpp_ad_Conv.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/lpp_apb_ad_conv.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/top_ad_conv.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_ad_Conv/top_ad_conv_RHF1401.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_amba/APB_MULTI_DIODE.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_amba/APB_SIMPLE_DIODE.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_amba/apb_devices_list.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_amba/lpp_amba.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_bootloader/bootrom.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_bootloader/lpp_bootloader.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_bootloader/lpp_bootloader_pkg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_cna/APB_CNA.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_cna/CNA_TabloC.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_cna/Convertisseur_config.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_cna/Gene_SYNC.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_cna/Serialize.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_cna/Systeme_Clock.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_cna/lpp_cna.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_demux/DEMUX.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_demux/lpp_demux.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_dma/fifo_latency_correction.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_dma/lpp_dma.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_dma/lpp_dma_apbreg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_dma/lpp_dma_fsm.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_dma/lpp_dma_ip.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_dma/lpp_dma_pkg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_dma/lpp_dma_send_16word.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_dma/lpp_dma_send_1word.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_Header/HeaderBuilder.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_Header/lpp_Header.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/ALU_Driver.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/ALU_Driver.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/APB_Matrix.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/Dispatch.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/DriveInputs.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/GetResult.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/MatriceSpectrale.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/MatriceSpectrale.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/Matrix.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/ReUse_CTRLR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/SpectralMatrix.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/SpectralMatrix.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/Starter.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/TopMatrix_PDR.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/TopSpecMatrix.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/Top_MatrixSpec.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_matrix/lpp_matrix.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/APB_FIFO.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/APB_FIFO.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/FIFO_pipeline.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/FillFifo.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/SSRAM_plugin.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/SSRAM_plugin_vsim.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/lppFIFOxN.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/lppFIFOxN.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/lpp_FIFO.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/lpp_memory.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_memory/lpp_memory.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_lfr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_lfr_apbreg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_lfr_filter.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_lfr_ms.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_lfr_pkg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_top_acq.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_top_acq.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_top_apbreg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_top_lfr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_top_lfr_pkg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_top_lfr_pkg.vhd.bak
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_top_lfr_wf_picker.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_top_lfr_wf_picker_ip.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/lpp_top_lfr_wf_picker_ip_whitout_filter.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_top_lfr/top_wf_picker.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_uart/APB_UART.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_uart/BaudGen.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_uart/Shift_REG.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_uart/UART.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_uart/lpp_uart.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_usb/APB_USB.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_usb/FX2_Driver.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_usb/FX2_WithFIFO.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_usb/RWbuf.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_usb/lpp_usb.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_burst.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_dma.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_dma_genvalid.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_dma_selectaddress.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_dma_send_Nword.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_fifo.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_fifo_arbiter.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_fifo_ctrl.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_pkg.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_snapshot.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_snapshot_controler.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./lpp_waveform/lpp_waveform_valid_ack.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./Rocket_PCM_Encoder/MinF_Cntr.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./Rocket_PCM_Encoder/Rocket_PCM_Encoder.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./Rocket_PCM_Encoder/Serial_Driver.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./Rocket_PCM_Encoder/Serial_Driver_Multiplexor.vhd
add_input_file -format VHDL -work lpp ../../../grlib-gpl-1.1.0-b4108/lib/../../VHD_Lib/lib/lpp/./Rocket_PCM_Encoder/Word_Cntr.vhd
add_input_file -format VHDL -work work config.vhd
add_input_file -format VHDL -work work ahbrom.vhd
add_input_file -format VHDL -work work leon3mp.vhd
setup_design -design top
setup_design -retiming
setup_design -vhdl
setup_design -transformations=false
setup_design -compile_for_timing=true
setup_design -frequency="50"

save_impl
