
--=================================================================================
--THIS FILE IS GENERATED BY A SCRIPT, DON'T TRY TO EDIT
--
--TAKE A LOOK AT VHD_LIB/APB_DEVICES FOLDER TO ADD A DEVICE ID OR VENDOR ID
--=================================================================================


library ieee;
use ieee.std_logic_1164.all;
library grlib;
use grlib.amba.all;
use std.textio.all;


package apb_devices_list is


constant VENDOR_LPP   : amba_vendor_type := 16#19#;
 
constant ROCKET_TM   : amba_device_type := 16#1#;
constant otherCore   : amba_device_type := 16#2#;
constant LPP_SIMPLE_DIODE   : amba_device_type := 16#3#;
constant LPP_MULTI_DIODE   : amba_device_type := 16#4#;
constant LPP_LCD_CTRLR   : amba_device_type := 16#5#;
constant LPP_UART   : amba_device_type := 16#6#;
constant LPP_CNA   : amba_device_type := 16#7#;
constant LPP_APB_ADC   : amba_device_type := 16#8#;
constant LPP_CHENILLARD   : amba_device_type := 16#9#;
constant LPP_IIR_CEL_FILTER   : amba_device_type := 16#10#;
constant LPP_FIFO_PID   : amba_device_type := 16#11#;
constant LPP_FFT   : amba_device_type := 16#12#;
constant LPP_MATRIX   : amba_device_type := 16#13#;
constant LPP_BALISE   : amba_device_type := 16#14#;
constant LPP_USB   : amba_device_type := 16#15#;
constant LPP_DELAY   : amba_device_type := 16#16#;
constant LPP_DMA_TYPE   : amba_device_type := 16#17#;
constant LPP_BOOTLOADER_TYPE   : amba_device_type := 16#18#;
constant LPP_CLKSETTING   : amba_device_type := 16#20#;


end;
